### ISSUE TITLE
Documentation  planning - Plan the backlogs for this spring

### ISSUE THREAD

**Issue by savio591** [savio591/mce-onboarding-web#1]
Just plan and list data on this issue.

## Tasks to create the Backlogs

* [x] View the prototype on the [Figma]
* [x] List the possible pages on the next issues, describing all your possible components(do not think in technologies yet)
* [x] Think the database(off and before the MCE knowledge and study), auths with next.js
* [x] Init this env with next?? IDK, cause u need to use React... but, maybe it does not matter.
* [x] Order pages and your components to create.

[Figma]: https://www.figma.com/file/JSXslf24muuo1VVuCLSbeQ/Mind-Education-Copy
