### ISSUE TITLE
Component - Welcome user

### ISSUE THREAD

**Issue by savio591** [savio591/mce-onboarding-web#10]
Simple welcome user for user panel.

### Todo:
* [ ] Create the header with greetings and the name.
* [ ] Insert the image from Figma
* [ ] Prepare the HTML structure and styling for being the mobile version.

**Special style for mobile:**
* [ ] Follow the style in figma.
* [ ] Create the Logout button
* [ ] Insert email below welcome text
* [ ] Add the edit profile button below text.
