### ISSUE TITLE
Page - Login 🧑

### ISSUE THREAD

**Issue by savio591** [savio591/mce-onboarding-web#2]
Just create a simple and responsive login page. Follow the login prototype(but not exact diagramming, I've found some visual aspects issues.) 🔥

### Todo ✨

** Structures test **
* [x] Create a simple interface for the form

**Background:**
* [x] Fundo com a imagem do protótipo responsivo, porém não será visível na versão mobile.

**Caixa de login - Componente #3 **
* [x] Container estilo card(bordas arredondadas)
* [x] Verificar padding do container e espaçamento entre colunas da versão mobile e desktop
* [x] Criar o componente de input e a variação de entrada de senha(caracteres ocultos e opção de visualizar). As props do button devem ser passadas também.
* [x] Criar o componente de botão. Testar dependencia do height pelo padding, caso der problemas, o height deve ser fixado.
* [ ] Opcional(mas interessante): Adicionar login social abaixo do botão de login.
* [x] Link de registro como mostrado no protótipo.
* [x] Atenção nas diferenças entre a versão mobile e desktop.
