### ISSUE TITLE
Component - Sidebar

### ISSUE THREAD

**Issue by savio591** [savio591/mce-onboarding-web#7]
Simple sidebar with 2 variations: user and admin. Following the prototype

### Todo

**Both variations**
* [ ] Logo

**User sidebar**
* [ ] Email below logo
* [ ] Edit profile nav button

**Admin sidebar**
* [ ] Navugation categories title
* [ ] Categories nav
