### ISSUE TITLE
Component - Users list

### ISSUE THREAD

**Issue by savio591** [savio591/mce-onboarding-web#9]
List the users for the admin panel.

### Todo:
* [ ] Style the title
* [ ] Container for the list
* [ ] Create the list with ul li
* [ ] Style the list, try using the default ul li system, or, but test if you can use grids instead flexbox(see Diego's grid on Ignite).
